repos:
  - repo: https://github.com/pylint-dev/pylint
    rev: v2.17.7
    hooks:
      - id: pylint
        args: ['--rcfile=.pylintrc']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
          exclude: ^.*oui\.txt$
      -   id: trailing-whitespace
          exclude: ^.*oui\.txt$
